[build]
  command = "npm run build"         # Command to build your React app
  functions = "netlify/functions"   # Directory for Netlify serverless functions (optional)
  publish = "build"                 # Folder that contains your production build

# Redirect all routes to index.html for SPAs like React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

## Optional: Settings for Netlify Dev (local development)
#[dev]
#  command = "yarn start"           # Command to start your dev server (for local testing)
#  port = 3000                      # Port your dev server listens to
#  publish = "dist"                 # Folder with static content for _redirects file
